name: CI

on: [pull_request, push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  lint:
    name: Check code lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint
