name: CI

on: [pull_request, push]

jobs:
  test:
    name: Tests on node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 18, 'lts/*', 'latest']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  lint:
    name: Check code lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint
